name: Staging docker
on:
  workflow_dispatch:
jobs:
  build:
    name: Docker build
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: '${{ vars.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_PASSWORD }}'
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKER_REPO }}:${{ github.sha }}

      - name: Clone Private Repository
        uses: actions/checkout@v3
        with:
          repository: namgaytobden/manifest
          token: ${{ secrets.TOKEN }}
          path: manifest/
          ref: main

      - uses: namgaytobden/k8s-Manifestation-Beta@main
        with:
          image: ${{ vars.DOCKER_REPO }}:${{ github.sha }}
          manifest_path: manifest/deployment/

      - name: kubectl CLI Action
        uses: teknatha136/actions-kubectl@v1.0.0   
        with:
            kubectl-version: v1.27.3
            kube-config: ${{ secrets.KUBECONFIG }}                                
            run: | 
              kubectl --kubeconfig=.kube/config apply -f deployments/manifest/ -n k3d

    